name: Automatically generate documentation

# This workflow automatically generates documentation as dictated by control comments within the given markdown file
# * Set the input `readme` to specify which markdown file to update. Default `README.md`
# * Set the input `actionFilesPattern` to specify which action or workflow files are to be documented in the file. Default `action.yml`

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    uses: BJSS-Building-Blocks/devops/.github/workflows/generate-docs.yml@generate-docs-reusable-workflow
    with:
      actionFilesPattern: .github/workflows/*.yml
