name: Validate labels

# This workflow validates labels on the PR

on:
  pull_request:
    branches:
      - $default-branch
    types:
      # default pull_request triggers, plus `labeled` and `unlabeled`
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  enforce-version-labels:
    name: Enforce Version Labels
    uses: BJSS-Building-Blocks/devops/.github/workflows/enforce-version-labels.yml@v0
